[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['master']
  disabled = false
  pathPrefix = "/blog"
  customDomain = "easyhrworld.com"
  renderJavaScript = true